export const dummyData = {
  status: "success",
  totalResults: 22198,
  results: [
    {
      article_id: "2a13d4374f2364fd23251d1f9f4b02e4",
      title:
        "RG Kar Case Victim's Parents Slam CM Mamata Banerjee: 'Can't Disown Kolkata Police's Failure'",
      link: "https://news.abplive.com/cities/rg-kar-rape-murder-case-victim-parents-slam-cm-mamata-banerjee-can-t-disown-kolkata-police-failure-1746554",
      keywords: ["cities"],
      creator: [""],
      video_url: null,
      description:
        "RG Kar Case Victim's Parents Slam CM Mamata Banerjee: 'Can't Disown Kolkata Police's Failure'",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:24:47",
      pubDateTZ: "UTC",
      image_url:
        "https://feeds.abplive.com/onecms/images/uploaded-images/2025/01/25/10d1cd397c788866d65e1512d1f0da7d1737768226830272_original.jpg",
      source_id: "abplive",
      source_priority: 7754,
      source_name: "Abp News",
      source_url: "http://abplive.com",
      source_icon: "https://i.bytvi.com/domain_icons/abplive.jpg",
      language: "english",
      country: ["india"],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "189c8122098c8c8bb3375e436215e0e4",
      title: "Mexico refuses US deportation flight: Report",
      link: "https://www.deccanherald.com/world/mexico-refuses-us-deportation-flight-report-3372336",
      keywords: null,
      creator: ["Reuters"],
      video_url: null,
      description: null,
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:59",
      pubDateTZ: "UTC",
      image_url:
        "https://images.deccanherald.com/deccanherald%2F2025-01-25%2Ful8qlclz%2F2024newsmlRC2PN5AEEBFA1411225611.jpeg?ar=40%3A21&auto=format%2Ccompress&mode=crop&ogImage=true&rect=0%2C128%2C3427%2C1799&w=1200",
      source_id: "deccanherald",
      source_priority: 10080,
      source_name: "Deccan Herald",
      source_url: "https://www.deccanherald.com",
      source_icon: null,
      language: "english",
      country: ["india"],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "9a5596c4cbe26f23446899c917fec05d",
      title:
        "Trump administration officially changes name of 'Gulf of Mexico' to 'Gulf of America'",
      link: "https://economictimes.indiatimes.com/news/international/global-trends/trump-administration-officially-changes-name-of-gulf-of-mexico-to-gulf-of-america/articleshow/117540239.cms",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "The Trump administration's Interior Department officially renamed the Gulf of Mexico to the Gulf of America and Alaska's Denali peak to Mount McKinley. These changes were directed by President Trump as part of his executive actions post-inauguration. The renaming aims to honor former President McKinley and preserve the United States' heritage despite Mexico's contention regarding the internationally recognized name.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:54",
      pubDateTZ: "UTC",
      image_url:
        "https://img.etimg.com/thumb/msid-117540267,width-1200,height-630,imgsize-381240,overlay-economictimes/articleshow.jpg",
      source_id: "economictimes_indiatimes",
      source_priority: 231,
      source_name: "The Economic Times",
      source_url: "https://economictimes.indiatimes.com",
      source_icon:
        "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
      language: "english",
      country: ["india"],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "1d7415b9d2c2d979603d6abfc9251d11",
      title:
        "Do not sell your votes: Kejriwal tells voters, alleges BJP buying votes",
      link: "https://www.business-standard.com/elections/delhi-elections/do-not-sell-your-votes-kejriwal-tells-voters-alleges-bjp-buying-votes-125012401663_1.html",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "Kejriwal also assured the public that their vote remains confidential, urging them not to be intimidated by those trying to manipulate the election process",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:47",
      pubDateTZ: "UTC",
      image_url:
        "https://bsmedia.business-standard.com/_media/bs/img/article/default/1250124/thumb-125012401663.jpg",
      source_id: "business-standard",
      source_priority: 9158,
      source_name: "Business Standard",
      source_url: "https://www.business-standard.com",
      source_icon: "https://i.bytvi.com/domain_icons/business-standard.png",
      language: "english",
      country: ["india"],
      category: ["politics"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "6f8aa07bc89b5e8b2509c6dfc6243b48",
      title:
        "Moon Salutation Vs Sun Salutation: Discover The Unique Benefits Of Surya Namaskar And Chandra Namaskar",
      link: "https://www.thehealthsite.com/yoga/moon-salutation-vs-sun-salutation-1178686/",
      keywords: [
        "yoga",
        "chandra namaskar benefits",
        "moon salutation",
        "sun salutation surya namaskar",
        "benefits of sun salutation",
      ],
      creator: ["Tavishi Dogra"],
      video_url: null,
      description:
        "Embrace the sun’s vitality and the moon’s calm to create a balanced practice that supports your body and spirit.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:40",
      pubDateTZ: "UTC",
      image_url:
        "https://st1.thehealthsite.com/wp-content/uploads/2025/01/Moon-Salutation-Vs-Sun-Salutation.jpg",
      source_id: "thehealthsite",
      source_priority: 13386,
      source_name: "Thehealthsite",
      source_url: "https://www.thehealthsite.com",
      source_icon: "https://i.bytvi.com/domain_icons/thehealthsite.png",
      language: "english",
      country: ["india"],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "45c82886e2bfb2fa4865df511d0531a7",
      title:
        "A Letter to Myself Podcast: Deep in delinquency, a book he read in juvenile detention changed his life",
      link: "https://www.channelnewsasia.com/podcasts/deep-delinquency-book-juvenile-detention-delonix-tan-third-gen-fishball-owner-4884351",
      keywords: ["podcasts ,singapore"],
      creator: null,
      video_url: null,
      description:
        "Trapped in a world of violence and delinquency during his teenage years, the third-generation owner of SanDai Fishball tells host Joel Chua how his past failures made him unafraid of taking risks.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:05",
      pubDateTZ: "UTC",
      image_url:
        "https://dam.mediacorp.sg/image/upload/s--9rTKhlO---/f_auto,q_auto/c_fill,g_auto,h_468,w_830/v1/mediacorp/cna/image/2024/10/23/a%20letter%20to%20mysself.jpg?itok=V18LwIOC",
      source_id: "channelnewsasia",
      source_priority: 4142,
      source_name: "Channel Newsasia",
      source_url: "https://www.channelnewsasia.com",
      source_icon: "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
      language: "english",
      country: [
        "georgia",
        "yemen",
        "afghanistan",
        "cyprus",
        "india",
        "singapore",
        "saudi arabia",
        "maldives",
        "japan",
        "united arab emirates",
        "malaysia",
        "china",
        "south korea",
        "north korea",
        "taiwan",
        "thailand",
        "pakistan",
        "mongolia",
        "brunei",
        "lebanon",
        "indonesia",
        "kyrgyzstan",
        "syria",
        "israel",
        "bhutan",
        "iran",
        "turkey",
        "armenia",
        "qatar",
        "philippines",
        "hong kong",
        "kazakhstan",
        "iraq",
        "bangladesh",
        "laos",
        "vietnam",
        "timor-leste",
        "kuwait",
        "myanmar",
        "azerbaijan",
        "jordan",
        "nepal",
        "sri lanka",
        "uzbekistan",
        "turkmenistan",
        "macau",
        "bahrain",
        "cambodia",
        "tajikistan",
        "oman",
      ],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "3a34e4d9b8da4272814ac209c7c5be67",
      title:
        "Bigg Boss 18: Karan Veer Mehra, Chum Darang hold hands during their first public appearance together [Watch Video]",
      link: "https://www.bollywoodlife.com/bigg-boss/bigg-boss-18-karan-veer-mehra-chum-darang-hold-hands-during-their-first-public-appearance-together-digvijay-rathee-joins-watch-viral-video-3065976/",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "All the ChumVeer fans were waiting for Karan Veer Mehra and Chum Darang's reunion post Bigg Boss 18. Last evening, the duo was spotted along with bestie Digvijay Rathee at Sandiip Sikcand's party.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:00",
      pubDateTZ: "UTC",
      image_url:
        "https://st1.bollywoodlife.com/wp-content/uploads/2025/01/Karan-Veer-28.png?h=900&impolicy=Medium_Widthonly&w=1280",
      source_id: "bollywoodlife",
      source_priority: 13281,
      source_name: "Bollywoodlife",
      source_url: "https://www.bollywoodlife.com",
      source_icon: "https://i.bytvi.com/domain_icons/bollywoodlife.png",
      language: "english",
      country: ["india"],
      category: ["entertainment"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "a83b6754431c4b3b5fc29df1209bf862",
      title:
        "A Letter to Myself Podcast: Deep in delinquency, a book he read changed his life",
      link: "https://www.channelnewsasia.com/podcasts/deep-delinquency-book-police-lock-up-delonix-tan-third-gen-fishball-owner-4884351",
      keywords: ["podcasts ,singapore"],
      creator: null,
      video_url: null,
      description:
        "Trapped in a world of violence and delinquency during his teenage years, the third-generation owner of SanDai Fishball tells host Joel Chua how his past failures made him unafraid of taking risks.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:23:00",
      pubDateTZ: "UTC",
      image_url:
        "https://dam.mediacorp.sg/image/upload/s--9rTKhlO---/f_auto,q_auto/c_fill,g_auto,h_468,w_830/v1/mediacorp/cna/image/2024/10/23/a%20letter%20to%20mysself.jpg?itok=V18LwIOC",
      source_id: "channelnewsasia",
      source_priority: 4142,
      source_name: "Channel Newsasia",
      source_url: "https://www.channelnewsasia.com",
      source_icon: "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
      language: "english",
      country: [
        "georgia",
        "yemen",
        "afghanistan",
        "cyprus",
        "india",
        "singapore",
        "saudi arabia",
        "maldives",
        "japan",
        "united arab emirates",
        "malaysia",
        "china",
        "south korea",
        "north korea",
        "taiwan",
        "thailand",
        "pakistan",
        "mongolia",
        "brunei",
        "lebanon",
        "indonesia",
        "kyrgyzstan",
        "syria",
        "israel",
        "bhutan",
        "iran",
        "turkey",
        "armenia",
        "qatar",
        "philippines",
        "hong kong",
        "kazakhstan",
        "iraq",
        "bangladesh",
        "laos",
        "vietnam",
        "timor-leste",
        "kuwait",
        "myanmar",
        "azerbaijan",
        "jordan",
        "nepal",
        "sri lanka",
        "uzbekistan",
        "turkmenistan",
        "macau",
        "bahrain",
        "cambodia",
        "tajikistan",
        "romania",
      ],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false,
    },
    {
      article_id: "1b94af8a914264e0c668a167706036f0",
      title:
        "Oak Valley Bancorp Reports 4th Quarter Results and Announces Cash Dividend",
      link: "https://in.investing.com/news/press-releases/oak-valley-bancorp-reports-4th-quarter-results-and-announces-cash-dividend-93CH-4629947",
      keywords: null,
      creator: ["Investing.com"],
      video_url: null,
      description: null,
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:22:05",
      pubDateTZ: "UTC",
      image_url:
        "https://i-invdn-com.investing.com/news/news_six_pile_108x81.jpg",
      source_id: "investing_in",
      source_priority: 1205,
      source_name: "Investing India",
      source_url: "https://in.investing.com",
      source_icon: null,
      language: "english",
      country: ["india"],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: true,
    },
    {
      article_id: "ea475cb803355144294bcdd4c4346182",
      title:
        "US military aircraft deport migrants as Pentagon readies more troops for border",
      link: "https://economictimes.indiatimes.com/news/international/global-trends/us-military-aircraft-deport-migrants-as-pentagon-readies-more-troops-for-border/articleshow/117540213.cms",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "U.S. military C-17 aircraft have begun deporting detained migrants to Guatemala, following President Trump's orders. The Pentagon is preparing to send additional troops, including from the 82nd Airborne Division, to the southern border. This marks the first use of military aircraft for migrant deportation in recent memory.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-25 01:21:56",
      pubDateTZ: "UTC",
      image_url:
        "https://img.etimg.com/thumb/width-1200,height-900,imgsize-68780,resizemode-75,msid-117540213/news/international/global-trends/us-military-aircraft-deport-migrants-as-pentagon-readies-more-troops-for-border.jpg",
      source_id: "economictimes_indiatimes",
      source_priority: 231,
      source_name: "The Economic Times",
      source_url: "https://economictimes.indiatimes.com",
      source_icon:
        "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
      language: "english",
      country: ["india"],
      category: ["top"],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: true,
    },
  ],
  nextPage: "1737768116080335534",
};
